replicaCount: 2

image:
  repository: gorshkovpsergey/user-srv

service:
  type: LoadBalancer
  port: 9000

externalPostgresql:
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  postgresqlHost: "postgres"
  postgresqlPort: "5432"
